services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - pgvolume:/var/lib/postgresql/data
volumes:
  pgvolume:
