server:
  error:
    include-stacktrace: never
spring:
  application:
    name: Springboot-essentials
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app: Spring boot 2 Essentials
  website: https://linkedin.com/in/edudu4
  github: https://github.com/edudu4



